---
- hosts: all
  become_user: root
  become_method: sudo
  roles:
    - role: env-common

- hosts: desktop
  become_user: root
  become_method: sudo
  roles:
    - role: env-desktop

- hosts: jukebox
  become_user: root
  become_method: sudo
  roles:
    - role: rfid-jukebox

- hosts: media_center
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast
    - role: mopidy

- hosts: media_player
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast

- hosts: raspberrypi
  become_user: root
  become_method: sudo
  roles:
    - role: raspberrypi
