---
- hosts: all
  become_user: root
  become_method: sudo
  roles:
    - role: env-common

- hosts: desktop
  become_user: root
  become_method: sudo
  roles:
    - role: env-desktop

- hosts: raspberrypi
  become_user: root
  become_method: sudo
  roles:
    - role: raspberrypi

- hosts: media_center
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast
    - role: mopidy
    #- role: kodi

- hosts: media_player
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast
